version: '3'
services:
  mongo:
    image: 'mongo:latest'
    container_name: mongo
    ports:
      - '${MONGO_PORT}:27017'
    volumes:
      - './data/mongodb:/data/db'
      - './log/mongodb:/var/log/mongodb'
      - './conf:/etc/mongo'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    networks:
      - mongo-net
  mongo-express:
    image: 'mongo-express:latest'
    container_name: mongo-express
    ports:
      - '${MONGO_EXPRESS_PORT}:8081'
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
    depends_on:
      - mongo
    networks:
      - mongo-net
networks:
  mongo-net:
    driver: bridge
    name: mongo-net