version: '3'

services:
  mysql-server:
    image: mysql:8.0.23
    container_name: mysql-server
    environment:
      TZ: 'Asia/Shanghai'
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - network-zabbix

  zabbix-server-mysql:
    image: zabbix/zabbix-server-mysql:ubuntu-5.0.0
    container_name: zabbix-server-mysql
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    privileged: true
    cap_add:
      - ALL
 #   restart: always
    environment:
      DB_SERVER_HOST: mysql-server
      DB_SERVER_PORT: 3306
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      ZBX_CACHESIZE: 4096M
      ZBX_VALUECACHESIZE: 128M
      TZ: 'Asia/Shanghai'
    ports:
      - '10051:10051'
    networks:
      - network-zabbix
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65000
      - net.ipv4.conf.all.accept_redirects=0
      - net.ipv4.conf.all.secure_redirects=0
      - net.ipv4.conf.all.send_redirects=0
    links:
      - mysql-server:mysql
    depends_on:
      - mysql-server
    volumes:
      #- zabbix-server-conf:/etc/zabbix
      - ./data/zabbix/alertscripts:/usr/lib/zabbix/alertscripts

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:ubuntu-5.0.0
    container_name: zabbix-web
    environment:
      DB_SERVER_HOST: mysql-server
      DB_SERVER_PORT: 3306
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      PHP_TZ: 'Asia/Shanghai'
      TZ: 'Asia/Shanghai'
#    restart: always
    ports:
      - '80:8080'
      - '443:8443'
    networks:
      - network-zabbix
    links:
      - mysql-server:mysql
      - zabbix-server-mysql:zabbix-server
    depends_on:
      - mysql-server
      - zabbix-server-mysql
    volumes:
      - /etc/localtime:/etc/localtime

  zabbix-agent:
    image: zabbix/zabbix-agent:ubuntu-5.0.0
    container_name: zabbix-agent
#    restart: always
    ports:
      - '10050:10050'
    networks:
      - network-zabbix
    environment:
      ZBX_HOSTNAME: 'Zabbix server'
      ZBX_SERVER_HOST: zabbix-server-mysql
      ZBX_SERVER_PORT: 10051


networks:
  network-zabbix:
    driver: bridge
