version: '3.7'

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: quay.io/minio/minio:${VERSION}
  command: server --console-address ":9001" http://minio{1...4}/data{1...2}
  expose:
    - "9000"
    - "9001"
  environment:
    TZ: ${TIMEZONE}
    MINIO_ROOT_USER: ${MINIO_ROOT_USER}
    MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
  healthcheck:
    test: ["CMD", "mc", "ready", "local"]
    interval: 5s
    timeout: 5s
    retries: 5
  restart: unless-stopped

# starts 4 docker containers running minio server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:
  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - /data/minio1/data1:/data1
      - /data/minio1/data2:/data1

  minio2:
    <<: *minio-common
    hostname: minio2
    volumes:
      - /data/minio2/data1:/data1
      - /data/minio2/data2:/data2

  minio3:
    <<: *minio-common
    hostname: minio3
    volumes:
      - /data/minio3/data1:/data1
      - /data/minio3/data2:/data2

  minio4:
    <<: *minio-common
    hostname: minio4
    volumes:
      - /data/minio4/data1:/data1
      - /data/minio4/data2:/data2

  nginx:
    image: nginx:1.25.3-alpine
    hostname: nginx
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4
    restart: unless-stopped

