version: '3'
services:
  haproxy:
    image: haproxy:alpine3.19
    environment:
      TZ: ${TIMEZONE}
    volumes:
      - ./conf/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./certs:/etc/ssl/private:ro
    ports:
      - "${PORT_SERVER}:8443"
    networks:
      - webnet
    privileged: true
    restart: unless-stopped
    healthcheck: 
      test: ["CMD", "haproxy", "-c", "-f", "/usr/local/etc/haproxy/haproxy.cfg"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging: 
      driver: json-file
      options:
        max-size: "500m"
        max-file: "3"

  nginx1:
    image: nginx:${VERSION}
    environment:
      TZ: ${TIMEZONE}
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/ssl/private:ro
      - ./html:/usr/share/nginx/html
      - /data/logs/nginx1:/var/log/nginx:rw 
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "nginx -t && ps aux | grep '[n]ginx: master process' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - webnet
    depends_on:
      - haproxy
    logging: 
      driver: json-file
      options:
        max-size: "300m"
        max-file: "3"

  nginx2:
    image: nginx:${VERSION}
    environment:
      TZ: ${TIMEZONE}
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/ssl/private:ro
      - ./html:/usr/share/nginx/html
      - /data/logs/nginx2:/var/log/nginx:rw 
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "nginx -t && ps aux | grep '[n]ginx: master process' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - webnet
    depends_on:
      - haproxy
    logging: 
      driver: json-file
      options:
        max-size: "300m"
        max-file: "3"

networks:
  webnet:
