version: '3'
services:
  minio1:
    image: minio/minio:${VERSION}
    container_name: minio1
    ports:
      - ${PORT_NODE1}:9000
#    restart: always
    environment:
      TZ: ${TIMEZONE}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    volumes:
      - ./data/minio1/1:/data1
      - ./data/minio1/2:/data2
      - ./conf/config1:/root/.minio
    command: server http://minio{1...4}/data{1...2}

  minio2:
    image: minio/minio:${VERSION}
    container_name: minio2
    ports:
      - ${PORT_NODE2}:9000
#    restart: always
    environment:
      TZ: ${TIMEZONE}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    volumes:
      - ./data/minio2/1:/data1
      - ./data/minio2/2:/data2
      - ./conf/config2:/root/.minio
    command: server http://minio{1...4}/data{1...2}

  minio3:
    image: minio/minio:${VERSION}
    container_name: minio3
    ports:
      - ${PORT_NODE3}:9000
#    restart: always
    environment:
      TZ: ${TIMEZONE}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    volumes:
      - ./data/minio3/1:/data1
      - ./data/minio3/2:/data2
      - ./conf/config3:/root/.minio
    command: server http://minio{1...4}/data{1...2} 

  minio4:
    image: minio/minio:${VERSION}
    container_name: minio4
    ports:
      - ${PORT_NODE4}:9000
#    restart: always
    environment:
      TZ: ${TIMEZONE}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    volumes:
      - ./data/minio4/1:/data1
      - ./data/minio4/2:/data2
      - ./conf/config4:/root/.minio
    command: server http://minio{1...4}/data{1...2}
