version: '3'
services:
  excalidraw:
    image: 'excalidraw/excalidraw:latest'
    container_name: excalidraw
#    restart: always
    ports:
      - '5000:80'
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - './data/web:/app/web'
